# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk: -openjdk12

# используем режим обычного пользователя для сборки проекта.
sudo: false

# Здесь используется сторонний сервис https://codecov.io/

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту yellowmouse8@protonmail.com если сборка упала
notifications:
  email:
    recipients:
      - yellowmouse8@protonmail.com
    on_success:  never # default: change
    on_failure: always # default: always
env:
  global:
    CODECOV_TOKEN="a1d162e2-488e-45bd-8183-d1ab390f703a"

